import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
			<title>Wastewater Intelligence Network</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Wastewater Intelligence Network</h1>
    </div>
  );
}
